import Foundation

/// The executable application state generated by `ILSpatialAppBuilder`.
public struct ILSpatialApp {
    private let startupTasks: [() async throws -> Void]
    
    init(startupTasks: [() async throws -> Void]) {
        self.startupTasks = startupTasks
    }
    
    /// Starts all registered asynchronous initialization tasks.
    public func start() async throws {
        for task in startupTasks {
            try await task()
        }
    }
}

/// A builder facade to simplify the initialization of ILSpatial packages in host apps.
public final class ILSpatialAppBuilder {
    private var startupTasks: [() async throws -> Void] = []
    
    public init() {}
    
    /// Executes a system registration closure.
    public func registerFeatureSystems(_ setup: () -> Void) -> Self {
        setup()
        return self
    }
    
    /// Executes a dependency registration closure.
    public func registerFeatureDependencies(_ setup: () -> Void) -> Self {
        setup()
        return self
    }
    
    /// Registers an asynchronous startup task to be executed when `start()` is called on the built app.
    public func onStart(_ setup: @escaping () async throws -> Void) -> Self {
        startupTasks.append(setup)
        return self
    }
    
    /// Finalizes setup and returns the executable `ILSpatialApp`.
    public func build() -> ILSpatialApp {
        return ILSpatialApp(startupTasks: startupTasks)
    }
}
